DoConstDwordMath_case dd DoConstDwordMath_tk_minus
		      dd DoConstDwordMath_tk_plus ; jump table for switch statement
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_tk_mult
		      dd DoConstDwordMath_tk_div
		      dd DoConstDwordMath_tk_mod
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_tk_rr
		      dd DoConstDwordMath_tk_ll
		      dd DoConstDwordMath_tk_rrminus
		      dd DoConstDwordMath_tk_llminus
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_tk_or
		      dd DoConstDwordMath_tk_and
		      dd DoConstDwordMath_tk_xor
		      dd DoConstDwordMath_case_end
		      dd DoConstDwordMath_tk_orminus
		      dd DoConstDwordMath_tk_andminus
		      dd DoConstDwordMath_tk_xorminus

DoConstMath_case      dd DoConstMath_tk_minus
		      dd DoConstMath_tk_plus ; jump table for switch statement
		      dd DoConstMath_case_end
		      dd DoConstMath_case_end
		      dd DoConstMath_tk_mult
		      dd DoConstMath_tk_div
		      dd DoConstMath_tk_mod
		      dd DoConstMath_case_end
		      dd DoConstMath_case_end
		      dd DoConstMath_case_end
		      dd DoConstMath_tk_rr
		      dd DoConstMath_tk_ll
		      dd DoConstMath_tk_rrminus
		      dd DoConstMath_tk_llminus
		      dd DoConstMath_case_end
		      dd DoConstMath_case_end
		      dd DoConstMath_case_end
		      dd DoConstMath_case_end
		      dd DoConstMath_tk_or
		      dd DoConstMath_tk_and
		      dd DoConstMath_tk_xor
		      dd DoConstMath_case_end
		      dd DoConstMath_tk_orminus
		      dd DoConstMath_tk_andminus
		      dd DoConstMath_tk_xorminus